package org.drools.examples.twittercbr

import ar.gov.anses.seginf.intrusos.parser.SyslogContentParser
import ar.gov.anses.seginf.intrusos.SyslogEvent
import java.text.MessageFormat

declare SyslogEvent
    @role( event )
    @timestamp( createdAt )
    @expires( 2s )
    user : String
end

rule "Dump messages"
when
    s : SyslogEvent( $user : user) from entry-point "syslog"
then
	s.setExecuted(true);
	System.out.println($user);
    System.out.println( MessageFormat.format( "[{0,time,full}] @{1}",
                                              s.getSubsystem(),
                                              s.getUser() ) );
         System.out.println("CORRARELO2");
    update(s);
end

