package org.drools.examples.twittercbr

import ar.gov.anses.seginf.intrusos.parser.SyslogContentParser
import ar.gov.anses.seginf.intrusos.SyslogEvent
import ar.gov.anses.seginf.intrusos.convert.*
import java.text.MessageFormat

declare SyslogEvent
    @role( event )
    @timestamp( createdAt )
    @expires( 10s )
    user : String
end

rule "Dump messages"
when
    $s : SyslogEvent(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	subsystem.toString matches ".*",
    	logMessage.toString matches ".*sudo.*"
    
    ) from entry-point "syslog"
    
     b : SyslogEvent(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	subsystem.toString matches ".*",
    	logMessage.toString matches ".*sudo.*",
    	this after [0s,10s] $s
    
    ) from entry-point "syslog"
    
then
	System.out.println("llama al same");
	$s.setExecuted(true);
	System.out.println(
		$s.getUser() + " " + 
		$s.getFacility() + " " + 
		$s.getSeverity() +" "+
		$s.getLogMessage());	
    update($s);
end

rule "Segunda regla"
when
    $s : SyslogEvent(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	subsystem.toString matches ".*",
    	logMessage.toString matches ".*sudo.*"
    
    ) from entry-point "syslog"
    
     b : SyslogEvent(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	subsystem.toString matches ".*",
    	logMessage.toString matches ".*sudo.*",
    	this after [0s,10s] $s
    
    ) from entry-point "syslog"
    
then
	System.out.println("manda un mensaje loco!!");
	$s.setExecuted(true);
    update($s);
end

