package org.drools.examples.twittercbr

import ar.gov.anses.seginf.intrusos.convert.*
import ar.gov.anses.seginf.intrusos.notification.*
import java.text.MessageFormat

declare SyslogMessage
    @role( event )
    @timestamp( createdAt )
    @expires( 10s )
end


rule "just logging"
no-loop true
when
    $s : SyslogMessage( ) from entry-point "syslog"
    
then
	System.out.println($s.toString());
	$s.setExecuted(true);
    update($s);
end



rule "Dump messages"
no-loop true
when
    $s : SyslogMessage(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	logMessage.toString matches ".*sudo.*"
    
    ) from entry-point "syslog"
    
    
     b : SyslogMessage(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	logMessage.toString matches ".*sudo.*",
    	this after [1ms,10s] $s
    
    ) from entry-point "syslog"
    
then
	System.out.println("ahora adohsahdkjsa!");
	$s.setExecuted(true);
	System.out.println(
		$s.getFacility() + " " + 
		$s.getSeverity() +" "+
		$s.getLogMessage());
	/*new Curl().invoke("http://10.192.54.85/anses/notify.php?via=sms&action=new&dst=005491160172120&msg=ladetuhermana&cod=6754");*/
    update($s);
end

rule "Segunda regla"
no-loop true
when
    $s : SyslogMessage(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	logMessage.toString matches ".*xp.*"
    
    ) from entry-point "syslog"
    
     b : SyslogMessage(
    
    	severity.toString matches ".*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	logMessage.toString matches ".*xp.*",
    	this after [1ms,10s] $s
    
    ) from entry-point "syslog"
    
then
	System.out.println("manda un mensaje loco!!");
	$s.setExecuted(true);
    update($s);
end



rule "SSH"
no-loop true
when
    $s : SyslogMessage(
    
    	severity.toString matches ".*CRITICAL.*",
    	facility.toString matches ".*",
    	hostname.toString matches ".*",
    	logMessage.toString matches ".*kernel.*ssh.*"
    
    ) from entry-point "syslog"
    
then
	System.out.println("ssh");
	new Curl().invoke("http://192.168.90.1/anses/notify.php?via=sms&action=new&dst=005491160172120&msg=ladetuhermana&cod=6754");
	$s.setExecuted(true);
    update($s);
end